version: '3.9'
services:
  mock-server:
    image: mockoon/cli:latest
    command: ["--data", "data", "--port", "3000"]
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:3000/your-healthcheck-route || exit 1"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 2
    #   start_period: 10s
    ports:
      # Serve the mocked API locally as available on port 8080
      - '3000:3000'
    volumes:
      - ./openapi.yml:/data:readonly