version: '3.9'
services:
  prism:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /openapi.yml'
    volumes:
      - ./openapi.yml:/openapi.yml:ro
    ports:
      # Serve the mocked API locally as available on port 8080
      - '8080:4010'