openapi: 3.0.3
info: 
  title: API
  version: v1
servers: 
  - url: reviews 
paths: 
  /reviews:
    get:
      description: Get bunch of reviews
      parameters: 
        - name: maxRating
          in:  query
          schema:
            type: number
      responses: 
        200:
          description: a bunch of reviews
          content: 
            application/json:
               schema: 
                 type: array
                 items: 
                   type: object
                   properties: 
                    rating:
                      type: integer
                      minimum: 1
                      maximum: 5
                    message:
                      type: string
                    uuid:
                      type: string
                      pattern: '^[0-9a-fA-F\-]{36}$'
                    userId:
                      type: string
                      pattern: '^[0-9a-fA-F\-]{36}$'
                      nullable: true
      
  